// Generated by CoffeeScript 1.3.3

module.exports = function(app) {
  return app.post('/request_help', function(req, res) {
    var location, team, technology, values, whats_up, _ref;
    values = (_ref = req.body, team = _ref.team, location = _ref.location, technology = _ref.technology, whats_up = _ref.whats_up, _ref);
    return res.render('help_request', values);
  });
};
