// Generated by CoffeeScript 1.3.3
var app, assets, express, port, _;

express = require('express');

assets = require('connect-assets');

_ = require('underscore');

app = express();

app.use(assets());

app.use(express.bodyParser());

app.use(express["static"](process.cwd() + '/public'));

app.set('view engine', 'jade');

app.get('/hello', function(req, res) {
  return res.send('Hello Node');
});

app.get('/hello/:name', function(req, res) {
  return res.send("Hello " + req.params.name);
});

(require('./more_examples'))(app);

(require('./prettify'))(app);

(require('./actions'))(app);

port = process.env.PORT || process.env.VMC_APP_PORT || 3000;

app.listen(port, function() {
  return console.log("Listening on " + port + "\nPress CTRL-C to stop server.");
});
