// Generated by CoffeeScript 1.3.3

module.exports = function(app) {
  var fib, fib_async;
  fib = function(n) {
    if (n <= 1) {
      return 1;
    } else {
      return (fib(n - 1)) + (fib(n - 2));
    }
  };
  app.get('/fib/:value', function(req, res) {
    return res.send(fib(req.params.value));
  });
  fib_async = function(n, callback) {
    if (n < 0) {
      return callback("Invalid Index " + n);
    } else if (n <= 1) {
      return callback(null, 1);
    } else {
      return fib_async(n - 1, function(err, n1) {
        if (err != null) {
          return callback(err);
        } else {
          return fib_async(n - 2, function(err, n2) {
            if (err != null) {
              return callback(err);
            } else {
              return callback(null, n1 + n2);
            }
          });
        }
      });
    }
  };
  app.get('/fib_async/:value', function(req, res) {
    return fib_async(req.params.value, function(err, val) {
      if (err != null) {
        return res.send(err, 400);
      } else {
        return res.send("" + val);
      }
    });
  });
  return app.get('/fib_async/:value', function(req, res) {
    return fib_async(req.params.value, function(err, val) {
      if (err != null) {
        return res.send(err, 400);
      } else {
        return res.send("" + val);
      }
    });
  });
};
