// Generated by CoffeeScript 1.3.3

module.exports = function(app) {
  var all_help_requests;
  all_help_requests = require('./persist').all_help_requests;
  return app.get('/help_me', function(req, res) {
    return all_help_requests(function(err, help_requests) {
      if (err != null) {
        return res.send(500, err);
      } else {
        return res.render('index', {
          help_requests: help_requests
        });
      }
    });
  });
};
